# Generated by Django 4.2.4 on 2023-08-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0006_alter_events_eventname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='placeid',
            new_name='coordinates',
        ),
    ]
